FCM 초기 SU
moiming/moiming-be pull request #8
Opened 2023-04-21 14:24 UTC by wrock-kang

<h2> Notification Domain 추가 </h2>

- 앱 내 활동으로 인해 발생할 Notification 들을 저장할 notification domain 추가
- 현재 생성만 작성됨. (조회, 삭제 까지만 추가될 예정) 
- 생성은 직접 생성이 아닌, 활동으로 인한 생성
- Notification Domain 은 어떤 활동의 알림인지, NotificationDomain Category 는 활동 내 어떤 알림인지에 대한 내용 (추후 알림 선택시 해당 활동 (모임, 정산활동, 일정 등) 으로 이동시켜줘야 하고, Category 는 알림 내용의 구체화를 위해 설정 )
</br>
<h2> FCM 활동 추가 1</h2>

- FCM 활동을 위한 Firebase Console 에서 제공해주는 admin key file 추가 (git ignore 필요할듯 함) 
- 사용자들 기기별로 FCM Token 이 생성되어야 하는데, Token 생성 로직은 Client side 에서 추가하고 토큰을 서버에 전달해 주는 방식으로 진행 
- FCM 기기토큰은  사용자 접속 (로그인, 자동로그인),  회원가입 진행마다 새로 발급받아 DB에 저장하되, 로그아웃시에는 DB에서 삭제한다  
- 기기 토큰 관리는 Client Side 미개발, Splash 화면 로직 미개발로 인해 대기 
- MainAppplication.java 파일에 앱 시작시 1회 Firebase Init 진행 (admin key file 로 진행됨) 
</br>
<h2> FCM 활동 추가 2 - FcmService Class 에 대해 </h2>

- 모든 FCM 을 보내는 Service Class
- 알림 제목, 알림 내용, 알림 대상만을 받고 정말 FCM 을 보내는 역할만 한다 
- 기기별 알림 전송이 구현되어 있으나, 단체 알림 전송 현재 미구현 (모임 대상, 정산활동 대상원들에 대해 구현 필요 예상) 
- 아직 FCM 관련되어서는 TEST 진행되지 않음 (기기별 FCM Token 구현 필요 - Client Side 개발 후 Test 필요) 

</br>
<h2> Notification 생성 - FCM 전송 활동 예시 추가 </h2>

- MoimMemberController 에서 모임 활동 가입 요청 처리에 대한 Notifcation - FCM 로직 예시로서 추가해둠
- Notification 이 필요한 시점에 NotificationDto를 생성하여 필요 Data 를 넣어 NotificationService 에 전달한다. 
- Notification Service 에서 필요한 title, body 등을 생성후, 저장한 다음에 FCM 을 생성한다. 
</br>

2023-04-30 11:17 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/model/dto/domain/NotificationDto.java
> +    private Long notificationId;
한번 셋팅된 후에 바뀌지 않을 값이기 때문에 final로 불변을 만드는 것도 좋을 것 같습니다.

2023-04-30 11:21 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +            notificationDto.setNotiCategory(NotificationDomainCategory.MOIM_DECLINE_MEMBER);
이런 동작을 하는 거라면 처음에 notificationDto()를 생성할 필요는 없을 것 같습니다. 
예를 들어 이렇게 빼는게 더 코드가 깔끔할지도?
```
if (memberMoimLinker.getMemberState().equals(MoimMemberState.DECLINE)) { // 거절
    NotificationDto.createMoimDeclineMember();
else if (memberMoimLinker.getMemberState().equals(MoimMemberState.ACTIVE)) { // 수락
    NotificationDto.createMoimNewMember()
 }
```

2023-04-30 11:22 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +        notificationService.createNotification(notificationDto, memberMoimLinker.getMember());
거절도 수락도 아닌 경우면 빈 알람이 갈 것 같네요.
만약 그런 케이스가 없다면, else if를 삭제하고 else절로 처리하는게 더 좋을 것 같네요.

2023-04-30 11:25 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +            if (notificationDto.getNotiCategory().equals(NotificationDomainCategory.MOIM_NEW_MEMBER)) {
서비스 클래스에서 너무 많은 일을 하는 것 같습니다.
알람 보내주는거 라면 다양한 클래스에서 많이 사용될 것 같은데, 알람 메세지를 만들어주는 클래스를 따로 만드는 것도 코드 깔끔하게 작성하는데 도움이 될 것 같습니다.

2023-04-30 11:27 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        Notification notification = Notification.createNotification(notificationDto.getSenderId()
복잡하니 생성하는 것 자체를 한 줄 짜리 메서드로 빼면 가독성에 도움 될 것 같습니다.
dto를 도메인으로 넘기는 건 좀 그러니..

2023-04-30 11:27 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
1. DB에 noti 저장되었는데, 메세지 발송에 실패한 경우
2. DB에 noti 저장되지 않았는데, 메세지 발송에 성공한 경우
이 경우에는 어떻게 동작하나요?

2023-04-30 11:30 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
1번 경우라면, IO Exception을 런타임에서 잡아서 FCM 알림 다시 보내는 경우를 재시도 해보아야 할 것 같은데요...! 2번 경우는 코드 살펴보면, 발생이 극히 드물 것 같긴 하네요.

2023-04-30 11:33 UTC, KafkaakfaK commented on src/main/resources/fcm/moiming-b2ae3-firebase-adminsdk-21zjr-11c77c69f7.json
> +  "type": "service_account",
나중에 여기 있는 Key는 환경 변수 같은 것들로 주입해야겠네요.
Github에 남아있으면 불의의 사고가...

2023-04-30 11:34 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/MoimingApplication.java
> +        FileInputStream serviceAccount =
나중에 이거 application.yaml 파일에서 주입 받아서 사용하는 쪽으로 가시죵.

2023-04-30 11:36 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/support/FcmService.java
> +    private String API_URL = "https://fcm.googleapis.com/v1/projects/moiming-b2ae3/messages:send";
```
private static final String API_URL = "https://fcm.googleapis.com/v1/projects/moiming-b2ae3/messages:send";
```
로 사용하는게 좋을 듯 합니다.

2023-04-30 11:41 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +            notificationDto.setNotiCategory(NotificationDomainCategory.MOIM_DECLINE_MEMBER);
그리고 조건문 자체도 이렇게 바꾸는게 깔끔할 것 같아요.
```
if (isDeclineMember()) { // 거절
    NotificationDto.createMoimDeclineMember();
else { // 수락
    NotificationDto.createMoimNewMember()
 }
```
이걸 줄이면 이렇게까지 가능하겠네요.
```
NotificationDto notificationDto =  isDeclineMember(memberMoimLinker) ? 
     NotificationDto.createMoimDeclineMember() : NotificationDto.createMoimNewMember();
```

2023-04-30 11:45 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
그리고 FCM 알림을 보낸 것도 좀... 확인해 볼, 혹은 염두해둬야 할 부분이 좀 있을 것 같습니다..! 
1. FCM 알림 자체가 비동기로 가는 경우 → 실패한 케이스를 어떻게 확인할 것인가?
2. FCM 알림 자체가 동기로 가는 경우 → 병목 구간이 될 가능성이 큼.

2023-04-30 13:18 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/model/dto/domain/NotificationDto.java
> +    private Long notificationId;
오우 이건 알고 있겠습니다!

2023-04-30 13:20 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +            notificationDto.setNotiCategory(NotificationDomainCategory.MOIM_DECLINE_MEMBER);
오우 마지막건 자바스크립트 할 때 보던 형식인데 자바에서도 쓰나보네요..? 처음 봤습니다. 
클린 코드 관점에서는 이게 나을 것 같긴하네요 ㅎㅎ

2023-04-30 13:22 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +        notificationService.createNotification(notificationDto, memberMoimLinker.getMember());
그런 케이스가 없을 테지만 정말 이상하게 발생하면 감지할 수 있도록 Exception 처리로 보내보겠습니다!

2023-04-30 13:24 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +            if (notificationDto.getNotiCategory().equals(NotificationDomainCategory.MOIM_NEW_MEMBER)) {
넵 추후 더 많은 알림이 도입됨에 따라서 형태를 더 갖춰나가야 할 것 같습니다. 처음부터 완벽한 인터페이스를 만들기가 어려워서 ㅠㅠ

2023-04-30 13:27 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
1. 생각하지 않았는데 callback 을 달아서 처리해놔도 될 것 같습니다. 그리고 FCM 실패는 그렇게 크게 관여하지 않는다고 하더라구요.
DB 에 저장되지 않을 일은 없지 않을까요? 

2. 아 두번째도 연관된 댓글이였군요 ㅎㅎ FCM 함수에서 Callback 을 만들든가 하면 될 것 같습니다. Failure Success Listener 형식으로.. 지원해줄 수도 있는데 살펴보고 없으면 콜백 만들어놓겠슴다 (근데 FCM 실패는 크게 관여하지 않는다고는 합니다) 

3.  FCM 은 All 비동기입니다! 그래서 보냈다는 사실만 가지고 보낸 스레드는 계속 진행하면 되어서, 비동기 방식에 대한 Failure Handler 를 등록해 놓으면 될 것 같습니다.

2023-04-30 14:45 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +            if (notificationDto.getNotiCategory().equals(NotificationDomainCategory.MOIM_NEW_MEMBER)) {
너무 크게는 생각하지 마시고...작업을 해보실 생각이 있으시다면 요 정도만 해도 괜찮을 듯 합니다. (반영 안하셔도 괜찮습니닷) 
1. 알람 메세지를 만들어주는 클래스 생성 (인터페이스 없이). 클래스에 공개 API는 execute() 정도 하나만?
2. 추후에 더 많은 알림이 도입되면, 해당 클래스를 인터페이스로 바꾸거나 추상 클래스로 변경해서 사용.

2023-04-30 14:47 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
@wrock-kang 님, 그럼 DB에는 이 알람을 왜 저장하는 걸까요?
저장한 다음에 사람들에게 주기적으로 해당 알람을 계속 보내는 걸까요? 이런 것이 아니라면 굳이 알람을 왜 저장하는지 잘 모르겠습니다. 설명해주시면 압도적 감사... 🙇

2023-05-01 09:22 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
알람을 저장해야 누구에게 보냈다는 알람이 저장되어서, 나중에 알람 받은 사람이 앱을 열었을 때 
> 알림목록 화면에 들어갈 경우 유저에게 수신된 알림 리스트들이 조회될 수 있기 때문이라고.. 생각했습니다..!!
> 별도의 FCM 을 보냈다는 사실 자체는 파이어베이스에 저장되지 않아서, 알람을 보냈고, 어떤 활동에서 어떤 요청을 보낸건지 ( NotificationDomain, NotificationCategory, notificationI) 를 저장해둬야 해당 알림을 눌렀을 때 그 활동으로 바로 접근할 수 있기 때문에.... 만들었.. 습니다!!!

2023-05-01 09:22 UTC, wrock-kang commented on src/main/resources/fcm/moiming-b2ae3-firebase-adminsdk-21zjr-11c77c69f7.json
> +  "type": "service_account",
ㅋㅋㅋㅋㅋㅋ 맞습니당 gitignore 에 넣으면 되지 않을까엽?

2023-05-01 09:23 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/MoimingApplication.java
> +        FileInputStream serviceAccount =
어엇 다른 방법을 모르겠던데 ㅠㅠ 괜찮은 방법 있으실까여

2023-05-01 09:23 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/support/FcmService.java
> +    private String API_URL = "https://fcm.googleapis.com/v1/projects/moiming-b2ae3/messages:send";
오우 맞네욥 ㅠㅠ 대문자로 해놓곸ㅋㅋㅋㅋ 감사합니다 :)

2023-05-01 09:24 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/support/FcmService.java
> +    private String API_URL = "https://fcm.googleapis.com/v1/projects/moiming-b2ae3/messages:send";
오우 근데 이걸 보고 static 이면 공유자원으로 쓰겠다는건데 public 이 자연스럽지 않나 싶어서  
private static 은 왜 필요하지..? 라는 생각이 들어서 검색해봤는데 좋은걸 배웠네욥.. 감사합니다 :)

2023-05-01 09:41 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +            notificationDto.setNotiCategory(NotificationDomainCategory.MOIM_DECLINE_MEMBER);
이 부분도 아래 답변드린 부분의 연장선으로  Notification 객체가 무슨 역할을 하는지 설명을 제가 안드려서 .. 
cretaeMoimDeclineMember(), createMoimNewMember() 이런 식으로 Constructor 를 만들다 보면 모든 알림 종류별로 만들어야 할 것 같아, 기존 방식을 유지하되, NotificationDto 를 default 로 생성해두는 방식이 별로라면 NotificationDomainCategory 만 유동적으로 바꾼 뒤에 마지막에 최종 set 해주는 방식으로 변경하겠습니ㅏㄷ.

2023-05-01 09:51 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        Notification notification = Notification.createNotification(notificationDto.getSenderId()
해당 DTO 클래스는 외부 통신시 응답 용도로 사용되는 클래스인데, 미정된 값들을 "", null 로하면서 생성 후 DTO 가 도메인으로 들어오는 방식은 좀 별로인 것 같습니다. 내부 Notification 생성시 정보들을 담아서 전달하기 위한 객체를 하나 더 만들어서 진행하도록 하겠습니다.

2023-05-01 10:02 UTC, wrock-kang commented on src/main/java/com/peoplein/moiming/service/NotificationService.java
> +        fcmService.sendSingleMessageTo(notification.getMember().getFcmToken()
failure handler 는 FCM 실패 사유에 따라서 다르게 해야할 것 같은데 .. 일단 logging 만 써놓도록 하고 넘기도록 하겟습니다. 다른 FCM 들 더 도입하면서 추가적으로 SU 하도록 하겟습니다. 
FcmService.java 에 sendSingleMessageTo 에 catch 로 에러 났음을 감지할 수 있도록은 해놨습니다. 
나중에 기기 Test 시 더 검증해보도록 하시죠!

2023-05-01 10:05 UTC, wrock-kang commented
생성쪽 좀 손보고 다시 커밋했습니다!

2023-05-01 14:06 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/MoimingApplication.java
> +        FileInputStream serviceAccount =
요렇게 사용하시면 됩니다.
``` 
// application.yaml
myapp:
  name: MyApp
  version: 1.0.0
```

// YOUR_CODE.java
```
public class hello {
  @Value(${myapp.name})
  private String hello;
  ...
}
```

2023-05-01 14:08 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/MoimMemberService.java
> +            notificationDto.setNotiCategory(NotificationDomainCategory.MOIM_DECLINE_MEMBER);
알림 종류가 많지 않을꺼라면 우선 메서드로 빼는 게 더 좋아 보입니다.
왜냐하면 저렇게 "", "" 값만 전달하다보면 NotificationDto가 무슨 종류의 Notification을 생성하는지 전혀 알 수가 없어서, 나중에 코드 수정할 때 읽기 어려울 것 같아요 😢

2023-05-01 14:11 UTC, KafkaakfaK commented on src/main/java/com/peoplein/moiming/service/support/FcmService.java
> +    private String API_URL = "https://fcm.googleapis.com/v1/projects/moiming-b2ae3/messages:send";
다른 곳에서도 사용되지 않을 필드라면, 굳이 public으로 Scope을 넓게 사용하지 않는 게 좋을 것 같아요. (책에서 그랬어요)
이유는 변경 시, 너무 많은 곳에 변경이 퍼져나가기 때문... 외려 수정할 때 골치 아플 수도...
최소한으로만 오픈하시죵.

2023-05-01 14:13 UTC, KafkaakfaK requested changes
그리고 조건문 자체도 이렇게 바꾸는게 깔끔할 것 같아요.

```
if (isDeclineMember()) { // 거절
    NotificationDto.createMoimDeclineMember();
else { // 수락
    NotificationDto.createMoimNewMember()
 }
```


이걸 줄이면 이렇게까지 가능하겠네요.
```
NotificationDto notificationDto =  isDeclineMember(memberMoimLinker) ? 
     NotificationDto.createMoimDeclineMember() : NotificationDto.createMoimNewMember();
```
/// 

이 부분은 의견 반영해주시면 좋을 것 같읍니다.
이유는 저렇게 "", "", null 값 전달해서 Dto를 생성하면, 해당 Dto가 어떤 역할을 하는지 Dto인지 전혀 알 수 없기 때문에 코드를 고쳐할 때, 코드 가독성이 매우 떨어질 것 같기 때문입니다.

2023-05-02 12:09 UTC, merged